include:
  - local: .gitlab-ci/includes/env-vars.yaml
  - local: .gitlab-ci/lint.yaml
  - local: .gitlab-ci/build.yaml
  - local: .gitlab-ci/test.yaml
  - local: .gitlab-ci/deploy.yaml

stages:
  - lint
  - build
  - test
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_COMMIT_BRANCH == "stg" && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_PIPELINE_SOURCE == "push"'

default:
  image: node:18
  cache:
    key: "$CI_COMMIT_REF_NAME-$(sha256sum package-lock.json | cut -d' ' -f1)"
    paths:
      - apis/node_modules/
  before_script:
    - cd apis
    - npm ci

variables:
  GIT_STRATEGY: clone
