include:
  - local: .gitlab-ci/lint.yml
  - local: .gitlab-ci/build.yml
  - local: .gitlab-ci/test.yml
  - local: .gitlab-ci/deploy.yml

stages:
  - lint
  - build
  - test
  - deploy

workflow:
  rules:
    # Start pipeline on pushes and MRs for these branches
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "stg" || $CI_COMMIT_BRANCH == "dev"'
      when: always

default:
  image: node:18
  cache:
    key: "$CI_COMMIT_REF_NAME-$(sha256sum package-lock.json | cut -d' ' -f1)"
    paths:
      - apis/node_modules/
  before_script:
    - cd apis
    - npm ci

variables:
  GIT_STRATEGY: clone
