build:
  stage: build
  <<: *set-env
  script:
    - echo "Building app for $DEPLOY_ENV..."
    - cd apis && npm run build
  artifacts:
    paths:
      - apis/dist/
  environment:
    name: $DEPLOY_ENV
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
