build:
  stage: build
  <<: *set-env
  script:
    - echo "Building app for $DEPLOY_ENV..."
    - cd apis && npm run build
  artifacts:
    paths:
      - apis/dist/
  environment:
    name: $DEPLOY_ENV
