.set-env: &set-env
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        DEPLOY_ENV: "prod"
    - if: '$CI_COMMIT_BRANCH == "stg"'
      variables:
        DEPLOY_ENV: "stg"
    - if: '$CI_COMMIT_BRANCH == "dev"'
      variables:
        DEPLOY_ENV: "dev"

lint:
  stage: lint
  <<: *set-env
  script:
    - echo "Running linter for $DEPLOY_ENV..."
    - cd apis && npm run lint
  environment:
    name: $DEPLOY_ENV
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
