.lint-template: &lint-template
  stage: lint
  script:
    - echo "Running linter for $DEPLOY_ENV..."
    - npm run lint

lint:prod:
  <<: *lint-template
  variables:
    DEPLOY_ENV: "prod"
  environment:
    name: prod
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'

lint:stg:
  <<: *lint-template
  variables:
    DEPLOY_ENV: "stg"
  environment:
    name: stg
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "stg" &&$CI_PIPELINE_SOURCE == "merge_request_event"'

lint:dev:
  <<: *lint-template
  variables:
    DEPLOY_ENV: "dev"
  environment:
    name: dev
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" && $CI_PIPELINE_SOURCE == "merge_request_event"'
