.test-template: &test-template
  stage: test
  script:
    - echo "Running tests for $DEPLOY_ENV..."
    - cd apis && ls -la dist/
    - npm run test
  dependencies:
    - build

test:prod:
  <<: *test-template
  variables:
    DEPLOY_ENV: "prod"
  environment:
    name: prod
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "merge_request_event"'

test:stg:
  <<: *test-template
  variables:
    DEPLOY_ENV: "stg"
  environment:
    name: stg
  rules:
    - if: '$CI_COMMIT_BRANCH == "stg" && $CI_PIPELINE_SOURCE == "merge_request_event"'

test:dev:
  <<: *test-template
  variables:
    DEPLOY_ENV: "dev"
  environment:
    name: dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_PIPELINE_SOURCE == "merge_request_event"'
