test:
  stage: test
  <<: *set-env
  script:
    - echo "Running tests for $DEPLOY_ENV..."
    - cd apis && ls -la dist/
    - npm run test
  dependencies:
    - build
  environment:
    name: $DEPLOY_ENV
